"""add is_recurring to transactions

Revision ID: 4f91f1de7b2d
Revises: e842ad525b9e
Create Date: 2026-05-23 03:20:36.230355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f91f1de7b2d'
down_revision: Union[str, Sequence[str], None] = 'e842ad525b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_recurring',
                  sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_recurring')
    # ### end Alembic commands ###
